### ISSUE TITLE
make flatland/flatland-book.ltx requires flatland/children.pm

### ISSUE THREAD

**Issue by anjakefala** [otherjoel/try-pollen#10] opened 2019-07-16 01:46 UTC
Hello!

I really love this project, and am currently exploring it in my quest to build a pollen pipeline for my own written works. =)

I am trying to get a working `make all` going, and keep running into this failure when the project tries to build the full flatland-book.ltx.

![Screenshot from 2019-07-15 18-43-14](https://user-images.githubusercontent.com/7489659/61259793-944f3b00-a730-11e9-9b03-e7625c61f5ae.png)

(I have the `xetex` LaTeX engine installed and have successfully built the individual pages leading up to here, albeit I have changed the fonts to Ubuntu and Ubuntu Mono.)

Does this error look familiar? Do you know what the `children.pm` that it is looking for is? I have not been able to find any reference to it in the repo.

**Comment by otherjoel** [comment] 2019-07-16 04:06
Thanks for letting me know! I am able to reproduce this issue. Something may have changed in Pollen since the last time I rebuilt the book. I’ll be looking into it.

**Comment by anjakefala** [comment] 2019-07-16 06:11
Ahhhh. Thank you! I do admit that I have not started looking into the pollen documentation in detail yet. I will also look into it, and let you know if I figured it out!

**Comment by otherjoel** [comment] 2019-07-16 14:56
I will say this much, there never has been a `children.pm`!

**Comment by otherjoel** [comment] 2019-07-16 16:12
Just pushed a fix, let me know if the problem persists.

**Closed as completed** 2019-07-16 16:11 UTC

**Comment by anjakefala** [comment] 2019-07-16 16:37
Fixed :tada: 

I appreciate you helping me out so promptly :blush:
